backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:

  - name: "pics"
    label: "Pics"
    folder: "src/pages/pics"
    create: true
    fields: 
       - {label: "Template Key", name: "templateKey", widget: "hidden", default: "pic"}
       - {label: "Image", name: "image", widget: "object", fields: [{label: "Image", name: "pic", widget: "image"}, {label: "Text Description", name: "alt", widget: "string"}]}


  - name: "vids"
    label: "Videos"
    folder: "src/pages/videos"
    create: true
    fields:
       - {label: "Template Key", name: "templateKey", widget: "hidden", default: "video"}
       - {label: "Url", name: "video", widget: "string"}


  - name: "calendar"
    label: "Upcoming Engagements"
    folder: "src/pages/calendar"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "engagement"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "dateTime", widget: "datetime"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Link to Event", name: "eventLink", widget: "string"}
      - {label: "Program", name: "program", widget: "markdown"}
      

  - name: "news"
    label: "News"
    folder: "src/pages/news"
    create: true
    fields: 
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Blurb", name: "blurb", widget: "string"}



  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        create: true
        fields: 
          - {label: "Template Key", name: "templateKey", widget}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/bio/index.md"
        label: "Bio"
        name: "bio"
        create: true
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        create: true
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
